-- =============================================================================
-- PATIENT PORTAL SECURITY MIGRATION
-- Items 1-4 from pilot-readiness security audit
-- =============================================================================
-- Addresses:
--   1. Add case_code to cases table (pseudonymous, non-sequential)
--   2. Join code token flow (replaces name+DOB patient identification)
--   3. Patient check-in via case_code (not raw caseId)
--   4. RLS enforcement on patient check-in (no more service role bypass)
-- =============================================================================


-- ─────────────────────────────────────────────────────────────────────────────
-- ITEM 1: Add case_code to cases table
-- ─────────────────────────────────────────────────────────────────────────────
-- case_code is a short, human-safe, non-sequential identifier.
-- Format: "EMP-XXXX" where XXXX is a random 4-char alphanumeric (base36).
-- Never derived from patient name, DOB, or any PII.

-- Helper: generate a random case_code
-- Rollback: drop function if exists generate_case_code();
create or replace function generate_case_code()
returns text
language plpgsql volatile
as $$
declare
  code text;
  attempts int := 0;
begin
  loop
    -- 6 random hex chars → ~16M possible codes
    code := 'EMP-' || upper(substr(md5(gen_random_uuid()::text), 1, 6));
    -- Ensure uniqueness
    if not exists (select 1 from cases where case_code = code) then
      return code;
    end if;
    attempts := attempts + 1;
    if attempts > 100 then
      raise exception 'Failed to generate unique case_code after 100 attempts';
    end if;
  end loop;
end;
$$;

-- Add column with default
-- Rollback: alter table cases drop column if exists case_code;
alter table cases add column if not exists case_code text unique;

-- Backfill existing rows that have null case_code
do $$
declare
  r record;
begin
  for r in select id from cases where case_code is null loop
    update cases set case_code = generate_case_code() where id = r.id;
  end loop;
end;
$$;

-- Make NOT NULL after backfill
alter table cases alter column case_code set not null;
alter table cases alter column case_code set default generate_case_code();

-- Index for lookups by case_code
-- Rollback: drop index if exists idx_cases_case_code;
create unique index if not exists idx_cases_case_code on cases (case_code);


-- ─────────────────────────────────────────────────────────────────────────────
-- JWT helper: extract case_code claim from patient JWT
-- ─────────────────────────────────────────────────────────────────────────────
-- Rollback: drop function if exists auth.case_code();
create or replace function auth.case_code()
returns text
language sql stable
as $$
  select coalesce(
    current_setting('request.jwt.claims', true)::json->>'case_code',
    (current_setting('request.jwt.claims', true)::json->'app_metadata'->>'case_code')
  );
$$;


-- ─────────────────────────────────────────────────────────────────────────────
-- ITEM 2: Join code token flow
-- ─────────────────────────────────────────────────────────────────────────────
-- join_codes table: one-time codes that map to a case_code.
-- Generated by therapist/admin, redeemed by patient.
-- Expires in 48h, single-use, rate-limited at API layer.

-- Rollback: drop table if exists join_codes;
create table if not exists join_codes (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  case_code text not null references cases(case_code) on update cascade,
  created_by uuid not null,             -- therapist or admin who generated it
  created_at timestamptz default now(),
  expires_at timestamptz not null default (now() + interval '48 hours'),
  redeemed_at timestamptz,              -- null until redeemed
  redeemed_by_ip inet,                  -- audit trail
  is_active boolean generated always as (
    redeemed_at is null and expires_at > now()
  ) stored
);

-- Index for code lookup
-- Rollback: drop index if exists idx_join_codes_code;
create index if not exists idx_join_codes_code on join_codes (code) where is_active;

-- Index for case_code lookup (find active codes for a case)
-- Rollback: drop index if exists idx_join_codes_case_code;
create index if not exists idx_join_codes_case_code on join_codes (case_code);

-- RLS on join_codes
alter table join_codes enable row level security;

-- Only therapists/admins who created the code can see it
-- Rollback: drop policy if exists join_codes_select on join_codes;
create policy join_codes_select on join_codes
  for select to authenticated
  using (
    auth.role() = 'admin'
    or created_by = auth.uid()
    or (auth.role() = 'manager' and exists (
      select 1 from cases c where c.case_code = join_codes.case_code
        and c.practice_id = auth.practice_id()
    ))
  );

-- Therapists/admins can create join codes for their cases
-- Rollback: drop policy if exists join_codes_insert on join_codes;
create policy join_codes_insert on join_codes
  for insert to authenticated
  with check (
    auth.role() = 'admin'
    or exists (
      select 1 from cases c where c.case_code = join_codes.case_code
        and c.therapist_id = auth.uid()
    )
    or (auth.role() = 'manager' and exists (
      select 1 from cases c where c.case_code = join_codes.case_code
        and c.practice_id = auth.practice_id()
    ))
  );

-- Redemption is done via service role (API verifies code → mints JWT)
-- No update policy for authenticated — only service role can mark redeemed


-- ─────────────────────────────────────────────────────────────────────────────
-- Rate limiting table for join code attempts
-- ─────────────────────────────────────────────────────────────────────────────
-- Rollback: drop table if exists join_code_attempts;
create table if not exists join_code_attempts (
  id uuid primary key default gen_random_uuid(),
  ip inet not null,
  attempted_at timestamptz default now()
);

-- Index for rate limit queries
-- Rollback: drop index if exists idx_join_code_attempts_ip_time;
create index if not exists idx_join_code_attempts_ip_time
  on join_code_attempts (ip, attempted_at desc);

-- No RLS needed — only service role accesses this table
alter table join_code_attempts enable row level security;
-- No policies = no authenticated access (service role only)


-- ─────────────────────────────────────────────────────────────────────────────
-- Audit log table for join code events
-- ─────────────────────────────────────────────────────────────────────────────
-- Rollback: drop table if exists portal_audit_log;
create table if not exists portal_audit_log (
  id uuid primary key default gen_random_uuid(),
  event text not null,                  -- 'join_code_redeemed', 'join_code_failed', 'checkin_submitted'
  case_code text,
  ip inet,
  metadata jsonb default '{}',
  created_at timestamptz default now()
);

-- Index for querying by event type
-- Rollback: drop index if exists idx_portal_audit_log_event;
create index if not exists idx_portal_audit_log_event
  on portal_audit_log (event, created_at desc);

-- RLS: admin only
alter table portal_audit_log enable row level security;

-- Rollback: drop policy if exists portal_audit_log_admin_select on portal_audit_log;
create policy portal_audit_log_admin_select on portal_audit_log
  for select to authenticated
  using (auth.role() = 'admin');


-- ─────────────────────────────────────────────────────────────────────────────
-- ITEM 3 & 4: Update checkins RLS — patient inserts via case_code claim
-- ─────────────────────────────────────────────────────────────────────────────
-- Drop existing checkins_insert policy (it used auth.uid() = patient_id,
-- which required service role bypass for unauthenticated patients).
-- Replace with case_code-scoped policy.

-- Rollback: create policy checkins_insert ...  (restore original from harden migration)
drop policy if exists checkins_insert on checkins;

-- New policy: patient can insert checkins where their JWT case_code matches
-- the case_code on the case that the checkin belongs to.
-- Therapists can also insert (for therapist-initiated check-ins).
-- Rollback: drop policy if exists checkins_insert_v2 on checkins;
create policy checkins_insert_v2 on checkins
  for insert to authenticated
  with check (
    auth.role() = 'admin'
    -- Patient: JWT case_code must match the case's case_code
    or (auth.role() = 'patient' and exists (
      select 1 from cases c
      where c.id = checkins.case_id
        and c.case_code = auth.case_code()
    ))
    -- Therapist: can insert for their own cases
    or (auth.role() = 'therapist' and exists (
      select 1 from cases c
      where c.id = checkins.case_id
        and c.therapist_id = auth.uid()
    ))
  );

-- Also update checkins select to support case_code for patients
-- (existing policy already supports patient_id = auth.uid(), add case_code path)
drop policy if exists checkins_select on checkins;

-- Rollback: restore original checkins_select from harden migration
create policy checkins_select_v2 on checkins
  for select to authenticated
  using (
    auth.role() = 'admin'
    or exists (
      select 1 from cases c
      where c.id = checkins.case_id
        and (
          c.therapist_id = auth.uid()
          or c.patient_id = auth.uid()
          or c.case_code = auth.case_code()
          or (auth.role() = 'manager' and c.practice_id = auth.practice_id())
        )
    )
  );

-- Update cases_select to also allow patient access via case_code JWT claim
drop policy if exists cases_select on cases;

-- Rollback: restore original cases_select from harden migration
create policy cases_select_v2 on cases
  for select to authenticated
  using (
    auth.role() = 'admin'
    or therapist_id = auth.uid()
    or patient_id = auth.uid()
    or case_code = auth.case_code()
    or (auth.role() = 'manager' and practice_id = auth.practice_id())
  );

-- Update goals_select to support case_code for patients
drop policy if exists goals_select on goals;

-- Rollback: restore original goals_select from harden migration
create policy goals_select_v2 on goals
  for select to authenticated
  using (
    auth.role() = 'admin'
    or exists (
      select 1 from cases c
      where c.id = goals.case_id
        and (
          c.therapist_id = auth.uid()
          or c.patient_id = auth.uid()
          or c.case_code = auth.case_code()
          or (auth.role() = 'manager' and c.practice_id = auth.practice_id())
        )
    )
  );


-- =============================================================================
-- ROLLBACK SCRIPT (run these in reverse order to undo this migration)
-- =============================================================================
-- drop policy if exists goals_select_v2 on goals;
-- create policy goals_select on goals ... (restore from 20260305_harden_rls_policies.sql)
-- drop policy if exists cases_select_v2 on cases;
-- create policy cases_select on cases ... (restore from 20260305_harden_rls_policies.sql)
-- drop policy if exists checkins_select_v2 on checkins;
-- create policy checkins_select on checkins ... (restore from 20260305_harden_rls_policies.sql)
-- drop policy if exists checkins_insert_v2 on checkins;
-- create policy checkins_insert on checkins ... (restore from 20260305_harden_rls_policies.sql)
-- drop policy if exists portal_audit_log_admin_select on portal_audit_log;
-- drop table if exists portal_audit_log;
-- drop table if exists join_code_attempts;
-- drop policy if exists join_codes_insert on join_codes;
-- drop policy if exists join_codes_select on join_codes;
-- drop table if exists join_codes;
-- drop function if exists auth.case_code();
-- drop index if exists idx_cases_case_code;
-- alter table cases alter column case_code drop not null;
-- alter table cases alter column case_code drop default;
-- alter table cases drop column if exists case_code;
-- drop function if exists generate_case_code();
